apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: httpbin-default-v1
spec:
  # Service that a client is requesting
  destination:
    name: httpbin
  precedence: 1
  route:
  # Service label to direct requests for httpbin
  - labels:
      version: v1
